CREATE TABLE MAHASISWA
( ID_MHS VARCHAR2(10),
  NAMA_MHS VARCHAR2(25),
  ALAMAT_MHS VARCHAR2(25),
  PRIMARY KEY (ID_MHS)
);

CREATE TABLE T_MATKUL
( ID_MATKUL VARCHAR2(5),
  NAMA_MATKUL VARCHAR2(20),
  PRIMARY KEY (ID_MATKUL)
);

CREATE TABLE TNILAI
( ID_MHS VARCHAR2(10),
  ID_MATKUL VARCHAR2(5),
  NILAI INT,
  FOREIGN KEY (ID_MHS) REFERENCES MAHASISWA(ID_MHS) ON DELETE CASCADE,
  FOREIGN KEY (ID_MATKUL) REFERENCES T_MATKUL(ID_MATKUL) ON DELETE CASCADE,
);

