/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package P4AgusRonaldo_15010;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import P4AgusRonaldo_15010.eNilai;
import P4AgusRonaldo_15010.cCari;
import javax.swing.JOptionPane;

/**
 *
 * @author Agus Ronaldo
 */
public class Form_Nilai extends javax.swing.JFrame {

    /**
     * Creates new form Form_Nilai
     */
    public Form_Nilai() {
        initComponents();
        tabelnilai();
    }

    
    public void tabelnilai(){
        DefaultTableModel tabbrg = new DefaultTableModel();
        tabbrg.addColumn("ID Mahasiswa");
        tabbrg.addColumn("ID Mata Kuliah");
        tabbrg.addColumn("Nilai");
        
        jTable1_nilai.setModel(tabbrg);
        
        try {
            Statement stat = (Statement)koneksi.getConnection().createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM TNILAI");
            while (result.next()){
                tabbrg.addRow(new Object[]{
                    result.getString("ID_MHS"),
                    result.getString("ID_MATKUL"), 
                    result.getString("NILAI"),
                });
                jTable1_nilai.setModel(tabbrg);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditampilkan");
        }
    }
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_idmhs = new javax.swing.JTextField();
        jTextField2_idmatkul = new javax.swing.JTextField();
        jTextField3_nilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_nilai = new javax.swing.JTable();
        jButton1_TAMBAH = new javax.swing.JButton();
        jButton2_UBAH = new javax.swing.JButton();
        jButton3_HAPUS = new javax.swing.JButton();
        jButton4_RESET = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATA NILAI MAHASISWA");

        jLabel2.setText("ID Mahasiswa");

        jLabel3.setText("ID Mata Kuliah");

        jLabel4.setText("Nilai");

        jTable1_nilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_nilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_nilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_nilai);

        jButton1_TAMBAH.setText("TAMBAH");
        jButton1_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_TAMBAHActionPerformed(evt);
            }
        });

        jButton2_UBAH.setText("UBAH");
        jButton2_UBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_UBAHActionPerformed(evt);
            }
        });

        jButton3_HAPUS.setText("HAPUS");
        jButton3_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_HAPUSActionPerformed(evt);
            }
        });

        jButton4_RESET.setText("RESET");
        jButton4_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_RESETActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2_UBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3_HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1_idmhs)
                                            .addComponent(jTextField2_idmatkul)
                                            .addComponent(jTextField3_nilai, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                        .addGap(127, 127, 127))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_idmhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2_idmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_TAMBAH)
                    .addComponent(jButton2_UBAH)
                    .addComponent(jButton3_HAPUS)
                    .addComponent(jButton4_RESET))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_TAMBAHActionPerformed
    eNilai nilai = new eNilai();
    nilai.setidmhs(jTextField1_idmhs.getText());
    nilai.setidmatkul(jTextField2_idmatkul.getText());
    nilai.setnilai(Integer.parseInt(jTextField3_nilai.getText()));
    
    cCari control = new cCari();
    control.tambahnilai(nilai);
    tabelnilai();
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton1_TAMBAHActionPerformed

    private void jButton2_UBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_UBAHActionPerformed
    eNilai nilai = new eNilai();
    nilai.setidmhs(jTextField1_idmhs.getText());
    nilai.setidmatkul(jTextField2_idmatkul.getText());
    nilai.setnilai(Integer.parseInt(jTextField3_nilai.getText()));
    
    cCari control = new cCari();
    control.ubahnilai(nilai);
    tabelnilai();
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton2_UBAHActionPerformed

    private void jButton3_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_HAPUSActionPerformed
    eNilai nilai = new eNilai();
    nilai.setidmhs(jTextField1_idmhs.getText());
    
    cCari control = new cCari();
    control.hapusnilai(nilai);
    tabelnilai();
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton3_HAPUSActionPerformed

    private void jButton4_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_RESETActionPerformed
    jTextField2_idmatkul.setText("");
    jTextField1_idmhs.setText("");
    jTextField3_nilai.setText("");
    }//GEN-LAST:event_jButton4_RESETActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Form_Mahasiswa tampil;
    tampil=new Form_Mahasiswa();
    tampil.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1_nilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_nilaiMouseClicked
    int baris = jTable1_nilai.getSelectedRow();
    if(baris==-1){
        JOptionPane.showMessageDialog(this, "Pilih Data");
    }else{
     jTextField1_idmhs.setText((String)jTable1_nilai.getValueAt(baris, 0));
     jTextField2_idmatkul.setText((String)jTable1_nilai.getValueAt(baris, 1));
     jTextField3_nilai.setText((String)jTable1_nilai.getValueAt(baris, 2));
    }
    }//GEN-LAST:event_jTable1_nilaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_TAMBAH;
    private javax.swing.JButton jButton2_UBAH;
    private javax.swing.JButton jButton3_HAPUS;
    private javax.swing.JButton jButton4_RESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_nilai;
    private javax.swing.JTextField jTextField1_idmhs;
    private javax.swing.JTextField jTextField2_idmatkul;
    private javax.swing.JTextField jTextField3_nilai;
    // End of variables declaration//GEN-END:variables
}
