/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package P4AgusRonaldo_15010;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import P4AgusRonaldo_15010.eMatKul;
import P4AgusRonaldo_15010.cCari;

/**
 *
 * @author Agus Ronaldo
 */
public class Form_MatKul extends javax.swing.JFrame {

    /**
     * Creates new form Form_MatKul
     */
    public Form_MatKul() {
        initComponents();
        tabelmatkul();
    }
    
    
    public void tabelmatkul(){
        DefaultTableModel tabbrg = new DefaultTableModel();
        tabbrg.addColumn("ID Mata Kuliah");
        tabbrg.addColumn("Nama Mata Kuliah");
        
        jTable1_tabmatkul.setModel(tabbrg);
        
        try {
            Statement stat = (Statement)koneksi.getConnection().createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM t_matkul");
            while (result.next()){
                tabbrg.addRow(new Object[]{
                    result.getString("ID_MATKUL"),
                    result.getString("NAMA_MATKUL"),              
                });
                jTable1_tabmatkul.setModel(tabbrg);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditampilkan");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_idmatkul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2_namamatkul = new javax.swing.JTextField();
        jButton1_TAMBAH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabmatkul = new javax.swing.JTable();
        jButton1_HAPUS = new javax.swing.JButton();
        jButton2_EDIT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2_RESET = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MATA KULIAH");

        jLabel2.setText("ID Mata Kuliah");

        jLabel3.setText("Nama Mata Kuliah");

        jButton1_TAMBAH.setText("TAMBAH");
        jButton1_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_TAMBAHActionPerformed(evt);
            }
        });

        jTable1_tabmatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_tabmatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_tabmatkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_tabmatkul);

        jButton1_HAPUS.setText("HAPUS");
        jButton1_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_HAPUSActionPerformed(evt);
            }
        });

        jButton2_EDIT.setText("EDIT");
        jButton2_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_EDITActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2_RESET.setText("RESET");
        jButton2_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_RESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1_HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1_idmatkul)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2_namamatkul, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_idmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2_namamatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_TAMBAH)
                    .addComponent(jButton1_HAPUS)
                    .addComponent(jButton2_EDIT)
                    .addComponent(jButton2_RESET))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_TAMBAHActionPerformed
    eMatKul matkul = new eMatKul();
    matkul.setidmtkul(jTextField1_idmatkul.getText());
    matkul.setnamamatkul(jTextField2_namamatkul.getText());
    
    cCari control = new cCari();
    control.tambahmatkul(matkul);
    tabelmatkul();
        jButton2_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton1_TAMBAHActionPerformed

    private void jButton2_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_EDITActionPerformed
    eMatKul matkul = new eMatKul();
    matkul.setidmtkul(jTextField1_idmatkul.getText());
    matkul.setnamamatkul(jTextField2_namamatkul.getText());
    
    cCari control = new cCari();
    control.ubahmatkul(matkul);
    tabelmatkul();
        jButton2_RESETActionPerformed(evt);
    
    }//GEN-LAST:event_jButton2_EDITActionPerformed

    private void jButton1_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_HAPUSActionPerformed
    eMatKul matkul = new eMatKul();
    matkul.setidmtkul(jTextField1_idmatkul.getText());
    
    cCari control = new cCari();
    control.hapusmatkul(matkul);
    tabelmatkul();
        jButton2_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton1_HAPUSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Form_Mahasiswa tampil;
    tampil=new Form_Mahasiswa();
    tampil.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1_tabmatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_tabmatkulMouseClicked
    int baris = jTable1_tabmatkul.getSelectedRow();
    if(baris==-1){
        JOptionPane.showMessageDialog(this, "Pilih Data");
    }else{
     jTextField1_idmatkul.setText((String)jTable1_tabmatkul.getValueAt(baris, 0));
     jTextField2_namamatkul.setText((String)jTable1_tabmatkul.getValueAt(baris, 1));
    }
    }//GEN-LAST:event_jTable1_tabmatkulMouseClicked

    private void jButton2_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_RESETActionPerformed
    jTextField1_idmatkul.setText("");
    jTextField2_namamatkul.setText("");
    }//GEN-LAST:event_jButton2_RESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MatKul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MatKul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MatKul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MatKul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_MatKul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_HAPUS;
    private javax.swing.JButton jButton1_TAMBAH;
    private javax.swing.JButton jButton2_EDIT;
    private javax.swing.JButton jButton2_RESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_tabmatkul;
    private javax.swing.JTextField jTextField1_idmatkul;
    private javax.swing.JTextField jTextField2_namamatkul;
    // End of variables declaration//GEN-END:variables
}
